// LuxeMart Product Data
// This file replaces the PHP/MySQL API call and works on any host including GitHub Pages & InfinityFree

const products = [
  // ─── FASHION ───────────────────────────────────────────────────────────────
  {
    id: 1,
    name: "Men's Classic Leather Jacket",
    category: "fashion",
    price: 8500,
    originalPrice: 12000,
    rating: 4.7,
    reviews: 128,
    img: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    desc: "Premium genuine leather jacket with a slim fit. Perfect for casual and semi-formal occasions.",
    brand: "UrbanEdge",
    colors: ["Black", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 2,
    name: "Women's Floral Summer Dress",
    category: "fashion",
    price: 3200,
    originalPrice: 4500,
    rating: 4.5,
    reviews: 94,
    img: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600&q=80",
    desc: "Light and breezy floral dress perfect for warm weather. Made from 100% breathable cotton.",
    brand: "BlossomWear",
    colors: ["Blue", "Pink", "White"],
    sizes: ["XS", "S", "M", "L"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 3,
    name: "Men's Slim Fit Chinos",
    category: "fashion",
    price: 2800,
    originalPrice: null,
    rating: 4.3,
    reviews: 67,
    img: "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&q=80",
    desc: "Modern slim-fit chinos made with stretch fabric for all-day comfort.",
    brand: "UrbanEdge",
    colors: ["Khaki", "Navy", "Olive"],
    sizes: ["28", "30", "32", "34", "36"],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 4,
    name: "Women's Oversized Hoodie",
    category: "fashion",
    price: 2200,
    originalPrice: 3000,
    rating: 4.8,
    reviews: 213,
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    desc: "Super soft oversized hoodie, perfect for lounging or casual outings.",
    brand: "CozyThreads",
    colors: ["Grey", "Black", "Pink"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },

  // ─── ELECTRONICS ────────────────────────────────────────────────────────────
  {
    id: 5,
    name: "Sony WH-1000XM5 Headphones",
    category: "electronics",
    price: 32000,
    originalPrice: 42000,
    rating: 4.9,
    reviews: 512,
    img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    desc: "Industry-leading noise cancellation with up to 30-hour battery life and crystal-clear sound.",
    brand: "Sony",
    colors: ["Black", "Silver"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 6,
    name: "Samsung 65\" 4K Smart TV",
    category: "electronics",
    price: 85000,
    originalPrice: 110000,
    rating: 4.6,
    reviews: 189,
    img: "https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=600&q=80",
    desc: "Crystal UHD 4K TV with built-in Alexa, multiple streaming apps and vivid colour display.",
    brand: "Samsung",
    colors: ["Black"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 7,
    name: "Apple AirPods Pro (2nd Gen)",
    category: "electronics",
    price: 28000,
    originalPrice: null,
    rating: 4.8,
    reviews: 743,
    img: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80",
    desc: "Active noise cancellation, transparency mode, adaptive audio and MagSafe charging case.",
    brand: "Apple",
    colors: ["White"],
    sizes: [],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 8,
    name: "JBL Charge 5 Bluetooth Speaker",
    category: "electronics",
    price: 12500,
    originalPrice: 16000,
    rating: 4.7,
    reviews: 324,
    img: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    desc: "Waterproof portable speaker with 20 hours of playtime and powerful bass.",
    brand: "JBL",
    colors: ["Black", "Blue", "Red"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },
  {
    id: 9,
    name: "iPhone 15 Pro Max",
    category: "electronics",
    price: 175000,
    originalPrice: null,
    rating: 4.9,
    reviews: 1024,
    img: "https://images.unsplash.com/photo-1696426505524-6e63e1d4e8d3?w=600&q=80",
    desc: "The most powerful iPhone ever with A17 Pro chip, titanium design and 48MP camera system.",
    brand: "Apple",
    colors: ["Natural Titanium", "Black Titanium", "White Titanium"],
    sizes: ["256GB", "512GB", "1TB"],
    inStock: true,
    onSale: false,
    badge: "New"
  },

  // ─── HOME & LIVING ──────────────────────────────────────────────────────────
  {
    id: 10,
    name: "Luxury Bedding Set (King)",
    category: "home",
    price: 6800,
    originalPrice: 9500,
    rating: 4.6,
    reviews: 87,
    img: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",
    desc: "Egyptian cotton 1000 thread count bedding set. Includes duvet cover, fitted sheet and 4 pillowcases.",
    brand: "DreamHome",
    colors: ["White", "Cream", "Grey"],
    sizes: ["King", "Queen"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 11,
    name: "Nespresso Vertuo Coffee Machine",
    category: "home",
    price: 14500,
    originalPrice: null,
    rating: 4.8,
    reviews: 256,
    img: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    desc: "One-touch coffee machine that brews 5 different cup sizes from espresso to alto.",
    brand: "Nespresso",
    colors: ["Black", "Silver"],
    sizes: [],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 12,
    name: "Minimalist Desk Lamp",
    category: "home",
    price: 3500,
    originalPrice: 5000,
    rating: 4.4,
    reviews: 112,
    img: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",
    desc: "Adjustable LED desk lamp with 5 colour temperatures, touch dimmer and USB charging port.",
    brand: "LumiHome",
    colors: ["Black", "White", "Gold"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },

  // ─── BEAUTY ─────────────────────────────────────────────────────────────────
  {
    id: 13,
    name: "Fenty Beauty Foundation",
    category: "beauty",
    price: 4200,
    originalPrice: null,
    rating: 4.7,
    reviews: 389,
    img: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    desc: "Full-coverage foundation available in 50 shades. Long-lasting, sweat-resistant formula.",
    brand: "Fenty Beauty",
    colors: ["Various"],
    sizes: ["30ml"],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 14,
    name: "The Ordinary Skincare Set",
    category: "beauty",
    price: 3800,
    originalPrice: 5200,
    rating: 4.6,
    reviews: 476,
    img: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=80",
    desc: "Complete skincare routine kit including Vitamin C, Hyaluronic Acid, Niacinamide and SPF.",
    brand: "The Ordinary",
    colors: [],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },
  {
    id: 15,
    name: "Dyson Airwrap Styler",
    category: "beauty",
    price: 52000,
    originalPrice: 65000,
    rating: 4.8,
    reviews: 631,
    img: "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=600&q=80",
    desc: "The iconic multi-styler that curls, waves, smooths and dries simultaneously without extreme heat.",
    brand: "Dyson",
    colors: ["Nickel/Copper", "Prussian Blue"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },

  // ─── SPORTS ─────────────────────────────────────────────────────────────────
  {
    id: 16,
    name: "Nike Dri-FIT Running Set",
    category: "sports",
    price: 4500,
    originalPrice: 6000,
    rating: 4.5,
    reviews: 203,
    img: "https://images.unsplash.com/photo-1535525153412-5a42439a210d?w=600&q=80",
    desc: "Lightweight moisture-wicking running top and shorts set. Ideal for long-distance runs.",
    brand: "Nike",
    colors: ["Black", "Blue", "Grey"],
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },
  {
    id: 17,
    name: "Yoga Mat Pro (6mm)",
    category: "sports",
    price: 2800,
    originalPrice: null,
    rating: 4.6,
    reviews: 178,
    img: "https://images.unsplash.com/photo-1601925228907-9c24af27ac5f?w=600&q=80",
    desc: "Non-slip, eco-friendly TPE yoga mat with alignment lines and carrying strap.",
    brand: "ZenFit",
    colors: ["Purple", "Blue", "Green"],
    sizes: [],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 18,
    name: "Adjustable Dumbbell Set (5-25kg)",
    category: "sports",
    price: 15000,
    originalPrice: 20000,
    rating: 4.7,
    reviews: 145,
    img: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600&q=80",
    desc: "Space-saving adjustable dumbbells that replace 9 pairs of weights. Quick-change dial system.",
    brand: "PowerFlex",
    colors: ["Black/Silver"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },

  // ─── KIDS ───────────────────────────────────────────────────────────────────
  {
    id: 19,
    name: "LEGO Technic Racing Car",
    category: "kids",
    price: 5500,
    originalPrice: null,
    rating: 4.9,
    reviews: 234,
    img: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&q=80",
    desc: "Advanced LEGO Technic set with 672 pieces. Great for kids aged 10 and up.",
    brand: "LEGO",
    colors: ["Multicolor"],
    sizes: [],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 20,
    name: "Kids' Waterproof Jacket",
    category: "kids",
    price: 2400,
    originalPrice: 3200,
    rating: 4.4,
    reviews: 89,
    img: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=600&q=80",
    desc: "100% waterproof and windproof kids jacket with reflective strips for safety.",
    brand: "KidZone",
    colors: ["Red", "Blue", "Yellow"],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },

  // ─── FOOTWEAR ────────────────────────────────────────────────────────────────
  {
    id: 21,
    name: "Nike Air Max 270",
    category: "footwear",
    price: 14500,
    originalPrice: 18000,
    rating: 4.8,
    reviews: 567,
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    desc: "Iconic Air Max cushioning in a sleek silhouette. Lightweight and built for all-day wear.",
    brand: "Nike",
    colors: ["White/Black", "Black/Red", "Triple White"],
    sizes: ["39", "40", "41", "42", "43", "44", "45"],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },
  {
    id: 22,
    name: "Adidas Ultraboost 23",
    category: "footwear",
    price: 16000,
    originalPrice: null,
    rating: 4.7,
    reviews: 412,
    img: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    desc: "Responsive Boost midsole with Primeknit upper for the ultimate running experience.",
    brand: "Adidas",
    colors: ["Core Black", "Cloud White", "Blue"],
    sizes: ["39", "40", "41", "42", "43", "44"],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 23,
    name: "Women's Block Heel Sandals",
    category: "footwear",
    price: 3800,
    originalPrice: 5500,
    rating: 4.3,
    reviews: 134,
    img: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    desc: "Elegant block heel sandals with cushioned footbed. Perfect for office and evening wear.",
    brand: "GlamStep",
    colors: ["Nude", "Black", "White"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    inStock: true,
    onSale: true,
    badge: "Sale"
  },

  // ─── WATCHES ─────────────────────────────────────────────────────────────────
  {
    id: 24,
    name: "Rolex Submariner (Homage)",
    category: "watches",
    price: 45000,
    originalPrice: 60000,
    rating: 4.8,
    reviews: 98,
    img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    desc: "Premium dive watch inspired by classic luxury timepieces. Stainless steel, sapphire crystal glass.",
    brand: "TimeMaster",
    colors: ["Silver/Black", "Gold/Blue"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Hot"
  },
  {
    id: 25,
    name: "Apple Watch Series 9",
    category: "watches",
    price: 55000,
    originalPrice: null,
    rating: 4.9,
    reviews: 823,
    img: "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600&q=80",
    desc: "The most advanced Apple Watch yet with double tap gesture, Siri on device and bright Always-On display.",
    brand: "Apple",
    colors: ["Midnight", "Starlight", "Product Red"],
    sizes: ["41mm", "45mm"],
    inStock: true,
    onSale: false,
    badge: "New"
  },
  {
    id: 26,
    name: "Casio G-Shock GA-2100",
    category: "watches",
    price: 12000,
    originalPrice: 15000,
    rating: 4.7,
    reviews: 445,
    img: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=600&q=80",
    desc: "Ultra-thin carbon core guard structure. Shock resistant, 200m water resistant, solar powered.",
    brand: "Casio",
    colors: ["Black", "White", "Camoflage"],
    sizes: [],
    inStock: true,
    onSale: true,
    badge: "Sale"
  }
];

// Make available globally
window.products = products;
